---
- name: restart_prometheus
  systemd:
    name: prometheus
    state: restarted
    enabled: yes
    daemon_reload: yes
- name: reload_prometheus
  systemd:
    name: prometheus
    state: reloaded

- name: systemd_reload
  systemd:
    daemon_reload: yes
...
