 
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
  config.vm.box_version = "2004.01"
  config.vm.provider "virtualbox" do |v|
      v.memory = 512
      v.cpus = 1
    end

  config.vm.define "sysd" do |sysd|
    sysd.vm.network "private_network", ip: "192.168.56.10", virtualbox__intnet: "net1"
    sysd.vm.hostname = "pam"
    sysd.vm.provision "shell", inline: <<-SHELL
    #Разрешаем подключение пользователей по SSH с использованием пароля
    sed -i 's/^PasswordAuthentication.*$/PasswordAuthentication yes/' /etc/ssh/sshd_config
    #Перезапуск службы SSHD
    systemctl restart sshd.service
    SHELL

  end

end
