 #Копирование файла конфигурации DHCP-сервера
  - name: set up dhcp-server
    template:
      src: dhcpd.conf
      dest: /etc/dhcp/dhcpd.conf
      mode: '0644'

#Перезапуск службы и добавление в автозагрузку
  - name: restart dhcp-server
    service:
      name: dhcpd
      state: restarted
      enabled: true
