---
- name: Create user prometheus
  user:
    name: prometheus
    create_home: no
    shell: /bin/false

- name: Create directories for prometheus
  file:
    path: "{{ item  }}"
    state: directory
    owner: prometheus
    group: prometheus
  loop:
    - '/tmp/prometheus'
    - '/etc/prometheus'
    - '/var/lib/prometheus'

- name: Download and Unzipped Prometheus
  unarchive:
    src: https://github.com/prometheus/prometheus/releases/download/v2.38.0/prometheus-2.38.0.linux-amd64.tar.gz
    dest: "/tmp/prometheus"
    remote_src: yes
    extra_opts: [--strip-components=1]

- name: Copy files
  copy:
    src: /tmp/prometheus/{{ item  }}
    dest: /usr/local/bin/
    remote_src: yes
    mode: preserve
    owner: prometheus
    group: prometheus
  loop: [ 'prometheus', 'promtool' ]

- name: Prometheus systemd file
  template:
    src: prometheus.j2
    dest: /etc/systemd/system/prometheus.service
  notify: systemd_reload

- name: prometheus configuration file
  template:
    src: prometheus.yml.j2
    dest: "{{ prometheus_dir_configuration }}/prometheus.yml"
    mode: 0755
    owner: prometheus
    group: prometheus
  notify: reload_prometheus

- name: start prometheus
  systemd:
    name: prometheus
    state: started
    enabled: yes

...
