# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
  config.vm.box_version = "2004.01"
#  config.vm.provision "ansible" do |ansible|
#    ansible.verbose = "vvv"
#    ansible.playbook = "playbook.yml"
#    ansible.become = "true"
#  end

  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 1
  end

  config.vm.define "web" do |web|
    web.vm.network "private_network", ip: "192.168.56.10", virtualbox__intnet: "net1"
    web.vm.hostname = "web"
    #nfss.vm.provision "shell", path: "nfss_script.sh"
  end

  config.vm.define "log" do |log|
    log.vm.network "private_network", ip: "192.168.56.11", virtualbox__intnet: "net1"
    log.vm.hostname = "log"
    #nfsc.vm.provision "shell", path: "nfsc_script.sh"
  end

end
