---
- name: Install Nginx and Node_Exporter
  hosts: web
  become: true
  roles:
  #- webserver
  - node-exporter

- name: Install Prometheus
  hosts: prometheus
  become: true
  roles:
    - prometheus
    - grafana
...
