# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
  config.vm.box_version = "2004.01"



  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 1
  end

  config.vm.define "web" do |web|
    web.vm.network "private_network", ip: "192.168.56.10", virtualbox__intnet: "net1"
    web.vm.hostname = "web"
    
  end

  config.vm.define "prometheus" do |prometheus|
    prometheus.vm.network "private_network", ip: "192.168.56.11", virtualbox__intnet: "net1"
    prometheus.vm.hostname = "prometheus"
    prometheus.vm.network "forwarded_port", guest:9090, host:9090
    prometheus.vm.network "forwarded_port", guest:3000, host:3000
    
  end

end
