---
# tasks file for updateos

# Upgrade RHEL family OS packages
  - name: Enable EPEL Repository on CentOS 7
    yum:
      name: epel-release
      state: latest
    when: ansible_os_family == "RedHat"
      
  - name: Upgrade RHEL Family OS packages
    yum:
      name: '*'
      state: latest
    when: ansible_os_family == "RedHat"

# Update Debian Family system
  - name: Update Debian Family system
    apt: 
      update_cache: yes
      upgrade: dist
      state: latest
      force_apt_get: yes
      cache_valid_time: 3600
      autoremove: yes
    when: ansible_os_family == "Debian"