---
- name: Add repository
  yum_repository:
    name: Grafana
    description: Grafana YUM repo
    baseurl: https://packages.grafana.com/oss/rpm
    gpgkey: https://packages.grafana.com/gpg.key
    gpgcheck: no
    sslverify: yes
    sslcacert: /etc/pki/tls/certs/ca-bundle.crt
- name: Install Grafana
  yum:
    name: grafana
    state: latest
#  notify:
#    - grafana systemd
- name: grafana start
  systemd:
    name: grafana-server
    enabled: yes
    state: started

#- name: start service grafana-server
#  systemd:
#    name: grafana-server
#    state: started
#    enabled: yes
- name: wait for service up
  uri:
    url: "http://127.0.0.1:3000"
    status_code: 200
  register: __result
  until: __result.status == 200
  retries: 120
  delay: 1
- name: change admin password for grafana gui
  shell : "grafana-cli admin reset-admin-password {{ grafana_admin_password }}"
  register: __command_admin
  changed_when: __command_admin.rc !=0
...
