# -*- mode: ruby -*-
# vim: set ft=ruby :
disk_controller = 'IDE' # MacOS. This setting is OS dependent. Details https://github.com/hashicorp/vagrant/issues/8105

MACHINES = {
  :otuslinuxzfs => {
        :box_name => "centos/7",
        :box_version => "2004.01",
        :ip_addr => '192.168.56.102',
    :disks => {
        :sata1 => {
            :dfile => '/home/roman/VMachines/otus/lesson5/sata1.vdi',
            :size => 512,
            :port => 1
        },
        :sata2 => {
            :dfile => '/home/roman/VMachines/otus/lesson5/sata2.vdi',
            :size => 512,
            :port => 2
        },
        :sata3 => {
            :dfile => '/home/roman/VMachines/otus/lesson5/sata3.vdi',
            :size => 512,
            :port => 3
        },
        :sata4 => {
            :dfile => '/home/roman/VMachines/otus/lesson5/sata4.vdi',
            :size => 512,
            :port => 4
        },       
        :sata5 => {
            :dfile => '/home/roman/VMachines/otus/lesson5/sata5.vdi',
            :size => 512,
            :port => 5
        },
        :sata6 => {
            :dfile => '/home/roman/VMachines/otus/lesson5/sata6.vdi',
            :size => 512,
            :port => 6
        },
        :sata7 => {
            :dfile => '/home/roman/VMachines/otus/lesson5/sata7.vdi',
            :size => 512,
            :port => 7
        },
        :sata8 => {
            :dfile => '/home/roman/VMachines/otus/lesson5/sata8.vdi',
            :size => 512,
            :port => 8
        }       
    }
  },
}

Vagrant.configure("2") do |config|

    config.vm.box_version = "1804.02"
    MACHINES.each do |boxname, boxconfig|
  
        config.vm.define boxname do |box|
  
            box.vm.box = boxconfig[:box_name]
            box.vm.host_name = "zfsotus"
  
            #box.vm.network "forwarded_port", guest: 3260, host: 3260+offset
  
            box.vm.network "private_network", ip: boxconfig[:ip_addr]
  
            box.vm.provider :virtualbox do |vb|
                    vb.customize ["modifyvm", :id, "--memory", "1024"]
                    needsController = false
            boxconfig[:disks].each do |dname, dconf|
                unless File.exist?(dconf[:dfile])
                  vb.customize ['createhd', '--filename', dconf[:dfile], '--variant', 'Fixed', '--size', dconf[:size]]
                                  needsController =  true
                            end
  
            end
                    if needsController == true
                       vb.customize ["storagectl", :id, "--name", "SATA", "--add", "sata" ]
                       boxconfig[:disks].each do |dname, dconf|
                           vb.customize ['storageattach', :id,  '--storagectl', 'SATA', '--port', dconf[:port], '--device', 0, '--type', 'hdd', '--medium', dconf[:dfile]]
                       end
                    end
            end
  
        box.vm.provision "shell", inline: <<-SHELL
          #install zfs repo
          yum install -y http://download.zfsonlinux.org/epel/zfs-release.el7_8.noarch.rpm
          #import gpg key 
          rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-zfsonlinux
          #install DKMS style packages for correct work ZFS
          yum install -y epel-release kernel-devel zfs
          #change ZFS repo
          yum-config-manager --disable zfs
          yum-config-manager --enable zfs-kmod
          yum install -y zfs
          #Add kernel module zfs
          modprobe zfs
          #install wget
          yum install -y wget
          SHELL
  
        end
    end
  end
