 
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
  config.vm.box_version = "2004.01"
#  config.vm.provision "ansible" do |ansible|
#    ansible.verbose = "vvv"
#    ansible.playbook = "playbook.yml"
#    ansible.become = "true"
#  end

  config.vm.provider "virtualbox" do |v|
    v.memory = 512
    v.cpus = 1
  end

  config.vm.define "sysd" do |sysd|
    sysd.vm.network "private_network", ip: "192.168.56.10", virtualbox__intnet: "net1"
    sysd.vm.hostname = "sysd-less9"
    sysd.vm.provision "shell", path: "sysd_script.sh"
  end

end
