# -*- mode: ruby -*-
# vi: set ft=ruby :
# export VAGRANT_EXPERIMENTAL="disks"

Vagrant.configure("2") do |config|

  config.vm.define "frontserver" do |frontserver|
    frontserver.vm.box = 'generic/debian11'
       
    frontserver.vm.host_name = 'frontserver'
    frontserver.vm.network :private_network, 
                       ip: "10.0.0.10", 
                       virtualbox__intnet: 'internalnet'
  
    # frontserver.vm.network "forwarded_port", guest: 80, host: 8081
    frontserver.vm.network :private_network, 
                       ip: "192.168.56.10",
                       adapter: 3
    frontserver.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      #vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    end
  
   
    # frontserver.vm.provision "ansible" do |ansible|
    #   ansible.playbook = "./ansible/roles/playbook-front.yml"
    #   ansible.become = "true"
    #   ansible.inventory_path = "./ansible/hosts/hostfront"
    #   ansible.host_key_checking = "false"
    #   ansible.limit = "all"
    # end
  
  end


  config.vm.define "mysqlservernode1" do |mysqlservernode1|
    mysqlservernode1.vm.box = 'centos/7'
       
    mysqlservernode1.vm.host_name = 'mysqlservernode1'
    mysqlservernode1.vm.network :private_network, 
                       ip: "10.0.0.20", 
                       virtualbox__intnet: 'internalnet'
  
    # frontserver.vm.network "forwarded_port", guest: 80, host: 8081
    # frontserver.vm.network :private_network, 
    #                    ip: "192.168.56.10",
    #                    adapter: 3
    mysqlservernode1.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      
    end
  
   
    # mysqlservernode1.vm.provision "ansible" do |ansible|
    #   ansible.playbook = "playbook-provision.yml"
    #   ansible.become = "true"
    #   ansible.inventory_path = "hosts"
    #   ansible.host_key_checking = "false"
    #   ansible.limit = "all"
    # end
  
  end
    

  config.vm.define "mysqlservernode2" do |mysqlservernode2|
    mysqlservernode2.vm.box = 'centos/7'
       
    mysqlservernode2.vm.host_name = 'mysqlservernode2'
    mysqlservernode2.vm.network :private_network, 
                       ip: "10.0.0.21", 
                       virtualbox__intnet: 'internalnet'
  
    # frontserver.vm.network "forwarded_port", guest: 80, host: 8081
    # frontserver.vm.network :private_network, 
    #                    ip: "192.168.56.10",
    #                    adapter: 3
    mysqlservernode2.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      
    end
  
   
    # mysqlservernode2.vm.provision "ansible" do |ansible|
    #   ansible.playbook = "playbook-provision.yml"
    #   ansible.become = "true"
    #   ansible.inventory_path = "hosts"
    #   ansible.host_key_checking = "false"
    #   ansible.limit = "all"
    # end
  
  end


  config.vm.define "backupserver" do |backupserver|
    backupserver.vm.box = 'centos/7'
       
    backupserver.vm.host_name = 'backupserver'
    backupserver.vm.network :private_network, 
                       ip: "10.0.0.30", 
                       virtualbox__intnet: 'internalnet'
  
    # frontserver.vm.network "forwarded_port", guest: 80, host: 8081
    # frontserver.vm.network :private_network, 
    #                    ip: "192.168.56.10",
    #                    adapter: 3
    backupserver.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      
    end
  
   
    # backupserver.vm.provision "ansible" do |ansible|
    #   ansible.playbook = "playbook-provision.yml"
    #   ansible.become = "true"
    #   ansible.inventory_path = "hosts"
    #   ansible.host_key_checking = "false"
    #   ansible.limit = "all"
    # end
  
  end
    
end